name: 'Setup Rust'
description: 'Setup Rust toolchain and cache'
inputs:
  components:
    description: 'Additional Rust components to install'
    required: false
    default: ''
runs:
  using: 'composite'
  steps:
    - name: Install Rust toolchain
      uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        components: ${{ inputs.components }}

    - name: Cache Rust dependencies
      uses: Swatinem/rust-cache@v2