"area: core":
  - "src/core/**"
"area: docs":
  - "docs/**"
"risk: high":
  - "Cargo.toml"
  - "src/main.rs"
"needs-design-review":
  - "src/core/**"
  - "src/lib.rs"
"area: testing":
  - "tests/**"
"area: ci":
  - ".github/**"
  - ".editorconfig"
  - ".gitattributes"
  - "renovate.json"
"area: governance":
  - "GOVERNANCE.md"
  - "MAINTAINERS.md"
