labels:
  - label: "area: core"
    matcher:
      files: ["src/core/**"]
  - label: "area: docs"
    matcher:
      files: ["docs/**"]
  - label: "risk: high"
    matcher:
      files: ["Cargo.toml", "src/main.rs"]
  - label: "needs-design-review"
    matcher:
      files: ["src/**"]
