- label: "area: core"
  files:
    - "src/core/**"

- label: "area: docs"
  files:
    - "docs/**"

- label: "risk: high"
  files:
    - "Cargo.toml"
    - "src/main.rs"

- label: "needs-design-review"
  files:
    - "src/core/**"
    - "src/lib.rs"

- label: "area: testing"
  files:
    - "tests/**"

- label: "area: ci"
  files:
    - ".github/**"
    - ".editorconfig"
    - ".gitattributes"
    - "renovate.json"

- label: "area: governance"
  files:
    - "GOVERNANCE.md"
    - "MAINTAINERS.md"
