labels:
  - label: "area: core"
    files:
      - "src/core/**"
  - label: "area: docs"
    files:
      - "docs/**"
  - label: "risk: high"
    files:
      - "Cargo.toml"
      - "src/main.rs"
  - label: "needs-design-review"
    files:
      - "src/**"
