# Copyright 2025 harpertoken
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: 'Features'
    labels:
      - feature
      - enhancement
  - title: 'Bug Fixes'
    labels:
      - fix
      - bugfix
      - bug
  - title: 'Documentation'
    labels:
      - documentation
      - docs
  - title: 'Maintenance'
    labels:
      - chore
      - maintenance
      - ci
      - dependencies
  - title: 'Security'
    labels:
      - security
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
version-resolver:
  major:
    labels:
      - major
  minor:
    labels:
      - minor
      - feature
      - enhancement
  patch:
    labels:
      - patch
      - fix
      - bugfix
      - bug
      - chore
      - maintenance
      - ci
      - dependencies
      - documentation
      - docs
      - security
  default: patch
template: |
  ## Changes

  $CHANGES
autolabeler:
  - label: 'feature'
    title: [ '/^feat/i' ]
  - label: 'enhancement'
    title: [ '/^feat/i', '/^perf/i' ]
  - label: 'fix'
    title: [ '/^fix/i' ]
  - label: 'bug'
    title: [ '/^fix/i' ]
  - label: 'bugfix'
    title: [ '/^fix/i' ]
  - label: 'documentation'
    title: [ '/^docs/i' ]
  - label: 'docs'
    title: [ '/^docs/i' ]
  - label: 'maintenance'
    title: [ '/^chore/i', '/^refactor/i', '/^style/i', '/^test/i', '/^build/i' ]
  - label: 'ci'
    title: [ '/^ci/i' ]
