filegroup(
    name = "zune_jpeg_neon_allow_unsafe.patch",
    srcs = ["zune_jpeg_neon_allow_unsafe.patch"],
)

filegroup(
    name = "zune_jpeg_avx2_unsafe.patch",
    srcs = ["zune_jpeg_avx2_unsafe.patch"],
)
