extends: default

# Copyright 2025 harpertoken
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

rules:
  # Allow longer lines for GitHub Actions workflows
  line-length:
    max: 140
    level: warning

  # Allow empty values in mappings (common in GitHub Actions)
  empty-values:
    forbid-in-block-mappings: false
    forbid-in-flow-mappings: false

  # Allow truthy values
  truthy:
    allowed-values: ['true', 'false', 'on', 'off', 'yes', 'no']
    check-keys: false

  # Allow comments to start anywhere
  comments-indentation: disable

  # Disable indentation check for GitHub Actions workflows
  indentation: disable

  # GitHub Actions specific allowances
  document-start: disable  # GitHub Actions doesn't require ---
  new-line-at-end-of-file: enable
  brackets: disable  # Allow spaces in brackets for readability
  comments:
    min-spaces-from-content: 1
