version: '3.8'

services:
  harper:
    build: .
    container_name: harper
    volumes:
      - harper_data:/app/data
    environment:
      - DATABASE_PATH=/app/data/harper.db
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - SAMBASTUDIO_API_KEY=${SAMBASTUDIO_API_KEY}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    stdin_open: true
    tty: true
    restart: unless-stopped

volumes:
  harper_data: