name: "PR checks"
description: "Basic PR validation for harpertoken"
runs:
  using: "composite"
  steps:
    - name: Check PR title format
      shell: bash
      run: |
        if [[ "${GITHUB_EVENT_NAME}" != "pull_request" ]]; then
          echo "Not a PR event, skipping title check."
          exit 0
        fi

        TITLE=$(jq -r '.pull_request.title' "$GITHUB_EVENT_PATH")

        echo "PR title: $TITLE"

        if [[ ! "$TITLE" =~ ^(build|chore|ci|docs|feat|fix|perf|refactor|revert|style|test)(\([^)]+\))?:\ .+ ]]; then
          echo "::error::PR title must follow Conventional Commits (e.g. fix(core): handle dt=0)"
          exit 1
        fi

        echo "PR title format OK"
