name: 'Check Titles'
description: 'Validate commit messages and PR titles'
runs:
  using: 'composite'
  steps:
    - name: Commitlint (on push)
      if: github.event_name == 'push'
      uses: wagoid/commitlint-github-action@v5
      with:
        configFile: 'ci/commitlint.config.js'

    - name: PR Title Check (on PR)
      if: github.event_name == 'pull_request'
      uses: thehanimo/pr-title-checker@v1.4.0
      with:
        GITHUB_TOKEN: ${{ github.token }}
        pass_on_octokit_error: false
        configuration_path: .github/pr-title-checker-config.json