# Copyright 2025 harpertoken
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: e2e
description: 'Run end-to-end tests on specified OS'
inputs:
  os:
    description: 'Operating system (ubuntu-latest, windows-latest, macos-latest)'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Install Rust
      uses: dtolnay/rust-toolchain@master
      with:
        toolchain: stable
        components: rustfmt, clippy

    - name: Install system dependencies (Ubuntu)
      if: inputs.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential pkg-config libsqlite3-dev
      shell: bash

    - name: Install system dependencies (macOS)
      if: inputs.os == 'macos-latest'
      run: |
        brew install sqlite3 pkg-config
      shell: bash

    - name: Cache Rust dependencies
      uses: Swatinem/rust-cache@v2
      with:
        cache-on-failure: true

    - name: Run E2E tests
      run: |
        cargo test --test integration -- --test-threads=1
        cargo test --test session_service_test
      shell: bash
      env:
        RUST_BACKTRACE: 1
        RUST_LOG: debug

    - name: Upload test logs on failure
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: test-logs-${{ inputs.os }}
        path: |
          **/test_*.log
          **/test-*.log
          **/test/*.log
        if-no-files-found: ignore
