name: Fix PR Title

on:
  pull_request:
    types: [opened, reopened, synchronize, edited]
    branches:
      - main

jobs:
  fix-pr-title:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: libnudget/title@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
